server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
      routes:
        - id: payment_routh
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service #lb:// 这是固定的   不太懂为啥
          predicates:
            - Path=/payment/get/**
            - After=2021-09-17T23:25:39.733+08:00[Asia/Shanghai]

        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - Cookie=name,yzm #curl http://localhost:9527/payment/lb --cookie "name=yzm"
#            - Header=X-Request-Id, \d+  #请求头为整数 curl http://localhost:9527/payment/lb -H "X-Request-Id:11"
#          filters:
#            - AddRequestHeader=X-Request-Red, Blue-{segent}
eureka:
  instance:
    hostname: cloud-gateway-gateway9527
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka   #单机版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版